### ISSUE TITLE
Support for Astro 2.0

### ISSUE THREAD

**Issue by polpielladev** [kevinzunigacuellar/pnpm-workspaces-template#32]
Hi @kevinzunigacuellar, hope you're doing well 👋

[Astro 2.0](https://astro.build/blog/astro-2/) came out yesterday and I have noticed that `astro-layouts` has `astro` as a peer dependency with version up to 1.7, which causes it to be incompatible with the new Astro version.

I was wondering if you were planning on supporting 2.0?

Thanks so much in advance, I love this package and would love to use it in my project for 2.0

Kind Regards,

Pol

**Comment by kevinzunigacuellar** [comment]
Hello @pol-piella 

Thanks for raising an issue. I was planning to take a look at Astro v2 this weekend. To answer your question, yes I am planning to add support for v2.

**Comment by kevinzunigacuellar** [comment]
updated in #34
